#!/usr/bin/env python3
"""
Agentic Workflow Example for Java Error Checker MCP Service

This example demonstrates how to use the MCP service in an agentic workflow
that generates Java project code incrementally across multiple stages.

Key features demonstrated:
- Session persistence across multiple generation stages
- Batch file writing for multiple classes per stage
- Session refresh to prevent timeout
- Incremental error checking after each stage
- Session info tracking
"""

import asyncio
import json
from pathlib import Path
from typing import List, Dict, Any

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client


class AgenticJavaCodeGenerator:
    """
    Simulates an agentic workflow that generates Java code incrementally.

    In a real agentic system, this would be driven by an LLM or planning agent
    that generates code in stages based on requirements and feedback.
    """

    def __init__(self, session: ClientSession):
        """Initialize the generator with an MCP session."""
        self.session = session
        self.session_id = None
        self.stage = 0

    async def initialize_project(self, project_name: str):
        """Stage 0: Initialize the project session."""
        print(f"\n{'='*60}")
        print(f"Stage {self.stage}: Initializing Project '{project_name}'")
        print(f"{'='*60}")

        result = await self.session.call_tool(
            "create_session",
            arguments={"project_name": project_name}
        )
        response = eval(result.content[0].text)
        self.session_id = response["session_id"]

        print(f"✓ Session created: {self.session_id}")
        print(f"  Project: {response['project_name']}")

        self.stage += 1

    async def generate_stage_1_models(self):
        """Stage 1: Generate data model classes."""
        print(f"\n{'='*60}")
        print(f"Stage {self.stage}: Generating Data Models")
        print(f"{'='*60}")

        # In a real agentic workflow, these would be generated by an LLM
        files = [
            {
                "file_path": "com/example/model/User.java",
                "content": """package com.example.model;

public class User {
    private String id;
    private String name;
    private String email;

    public User(String id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
"""
            },
            {
                "file_path": "com/example/model/Product.java",
                "content": """package com.example.model;

public class Product {
    private String id;
    private String name;
    private double price;

    public Product(String id, String name, double price) {
        this.id = id;
        this.name = name;
        this.price = price;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
}
"""
            }
        ]

        # Write multiple files in one batch
        result = await self.session.call_tool(
            "write_multiple_files",
            arguments={
                "session_id": self.session_id,
                "files": files
            }
        )
        response = eval(result.content[0].text)

        print(f"✓ Batch write complete:")
        print(f"  Files written: {response['written']}")
        print(f"  Files failed: {response['failed']}")

        # Check for errors
        await self.check_errors()

        # Refresh session to extend timeout
        await self.refresh_session()

        self.stage += 1

    async def generate_stage_2_services(self):
        """Stage 2: Generate service layer classes."""
        print(f"\n{'='*60}")
        print(f"Stage {self.stage}: Generating Service Layer")
        print(f"{'='*60}")

        files = [
            {
                "file_path": "com/example/service/UserService.java",
                "content": """package com.example.service;

import com.example.model.User;
import java.util.ArrayList;
import java.util.List;

public class UserService {
    private List<User> users;

    public UserService() {
        this.users = new ArrayList<>();
    }

    public void addUser(User user) {
        users.add(user);
    }

    public User getUserById(String id) {
        for (User user : users) {
            if (user.getId().equals(id)) {
                return user;
            }
        }
        return null;
    }

    public List<User> getAllUsers() {
        return new ArrayList<>(users);
    }

    public boolean removeUser(String id) {
        return users.removeIf(user -> user.getId().equals(id));
    }
}
"""
            },
            {
                "file_path": "com/example/service/ProductService.java",
                "content": """package com.example.service;

import com.example.model.Product;
import java.util.ArrayList;
import java.util.List;

public class ProductService {
    private List<Product> products;

    public ProductService() {
        this.products = new ArrayList<>();
    }

    public void addProduct(Product product) {
        products.add(product);
    }

    public Product getProductById(String id) {
        for (Product product : products) {
            if (product.getId().equals(id)) {
                return product;
            }
        }
        return null;
    }

    public List<Product> getAllProducts() {
        return new ArrayList<>(products);
    }

    public List<Product> getProductsByPriceRange(double minPrice, double maxPrice) {
        List<Product> result = new ArrayList<>();
        for (Product product : products) {
            if (product.getPrice() >= minPrice && product.getPrice() <= maxPrice) {
                result.add(product);
            }
        }
        return result;
    }
}
"""
            }
        ]

        result = await self.session.call_tool(
            "write_multiple_files",
            arguments={
                "session_id": self.session_id,
                "files": files
            }
        )
        response = eval(result.content[0].text)

        print(f"✓ Batch write complete:")
        print(f"  Files written: {response['written']}")
        print(f"  Files failed: {response['failed']}")

        await self.check_errors()
        await self.refresh_session()

        self.stage += 1

    async def generate_stage_3_main(self):
        """Stage 3: Generate main application class."""
        print(f"\n{'='*60}")
        print(f"Stage {self.stage}: Generating Main Application")
        print(f"{'='*60}")

        files = [
            {
                "file_path": "com/example/Main.java",
                "content": """package com.example;

import com.example.model.User;
import com.example.model.Product;
import com.example.service.UserService;
import com.example.service.ProductService;

public class Main {
    public static void main(String[] args) {
        // Initialize services
        UserService userService = new UserService();
        ProductService productService = new ProductService();

        // Create and add users
        User user1 = new User("1", "Alice", "alice@example.com");
        User user2 = new User("2", "Bob", "bob@example.com");
        userService.addUser(user1);
        userService.addUser(user2);

        // Create and add products
        Product product1 = new Product("P1", "Laptop", 999.99);
        Product product2 = new Product("P2", "Mouse", 29.99);
        Product product3 = new Product("P3", "Keyboard", 79.99);
        productService.addProduct(product1);
        productService.addProduct(product2);
        productService.addProduct(product3);

        // Display all users
        System.out.println("All Users:");
        for (User user : userService.getAllUsers()) {
            System.out.println("  " + user.getName() + " (" + user.getEmail() + ")");
        }

        // Display all products
        System.out.println("\\nAll Products:");
        for (Product product : productService.getAllProducts()) {
            System.out.println("  " + product.getName() + " - $" + product.getPrice());
        }

        // Find products in price range
        System.out.println("\\nProducts in $20-$100 range:");
        for (Product product : productService.getProductsByPriceRange(20.0, 100.0)) {
            System.out.println("  " + product.getName() + " - $" + product.getPrice());
        }
    }
}
"""
            }
        ]

        result = await self.session.call_tool(
            "write_multiple_files",
            arguments={
                "session_id": self.session_id,
                "files": files
            }
        )
        response = eval(result.content[0].text)

        print(f"✓ Batch write complete:")
        print(f"  Files written: {response['written']}")
        print(f"  Files failed: {response['failed']}")

        await self.check_errors()
        await self.refresh_session()

        self.stage += 1

    async def check_errors(self):
        """Check for compilation errors."""
        print(f"\n  Checking for compilation errors...")

        result = await self.session.call_tool(
            "check_errors",
            arguments={"session_id": self.session_id}
        )
        response = eval(result.content[0].text)

        if response["error_count"] == 0:
            print(f"  ✓ No compilation errors found!")
        else:
            print(f"  ⚠ Found {response['error_count']} error(s):")
            for i, error in enumerate(response["errors"], 1):
                print(f"\n    Error #{i}:")
                print(f"      File: {error['file']}")
                print(f"      Line: {error['line']}")
                print(f"      Message: {error['message']}")

    async def refresh_session(self):
        """Refresh the session to extend timeout."""
        result = await self.session.call_tool(
            "refresh_session",
            arguments={"session_id": self.session_id}
        )
        response = eval(result.content[0].text)
        print(f"  ✓ Session refreshed (timeout extended)")

    async def show_session_info(self):
        """Display session information."""
        print(f"\n{'='*60}")
        print(f"Final Session Information")
        print(f"{'='*60}")

        result = await self.session.call_tool(
            "get_session_info",
            arguments={"session_id": self.session_id}
        )
        response = eval(result.content[0].text)

        print(f"Session ID: {response['session_id']}")
        print(f"Project: {response['project_name']}")
        print(f"Workspace: {response['workspace_path']}")
        print(f"Age: {response['age_seconds']:.1f} seconds")
        print(f"Idle: {response['idle_seconds']:.1f} seconds")
        print(f"Total Files: {response['file_count']}")
        print(f"\nFiles:")
        for file in response['files']:
            print(f"  - {file}")

    async def cleanup(self):
        """Clean up the session when done."""
        print(f"\n{'='*60}")
        print(f"Cleaning Up")
        print(f"{'='*60}")

        result = await self.session.call_tool(
            "delete_session",
            arguments={"session_id": self.session_id}
        )
        response = eval(result.content[0].text)
        print(f"✓ {response['message']}")


async def run_agentic_workflow():
    """Run the complete agentic workflow."""
    print("="*60)
    print("Agentic Java Code Generation Workflow")
    print("="*60)
    print("\nThis example demonstrates:")
    print("  1. Multi-stage incremental code generation")
    print("  2. Batch file writing (multiple classes per stage)")
    print("  3. Session persistence across stages")
    print("  4. Automatic error checking after each stage")
    print("  5. Session refresh to prevent timeout")
    print("  6. Session info tracking")

    # Get the path to the server script
    server_path = Path(__file__).parent / "server.py"

    # Set up server parameters
    server_params = StdioServerParameters(
        command="python3",
        args=[str(server_path)],
        env=None
    )

    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()

            # Create the agentic generator
            generator = AgenticJavaCodeGenerator(session)

            try:
                # Execute the multi-stage workflow
                await generator.initialize_project("e-commerce-system")
                await generator.generate_stage_1_models()
                await generator.generate_stage_2_services()
                await generator.generate_stage_3_main()

                # Show final session info
                await generator.show_session_info()

            finally:
                # Always cleanup
                await generator.cleanup()

            print(f"\n{'='*60}")
            print("Workflow completed successfully!")
            print(f"{'='*60}")


def main():
    """Main entry point."""
    asyncio.run(run_agentic_workflow())


if __name__ == "__main__":
    main()
